# Generated by Django 6.0.7 on 2026-09-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEnvironmentalObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('provider', models.CharField(help_text='Name of the external data provider.', max_length=100)),
                ('data_type', models.CharField(choices=[('GRID_CARBON_INTENSITY', 'Grid Carbon Intensity')], help_text='Type of environmental observation.', max_length=50)),
                ('zone', models.CharField(help_text='External provider zone identifier.', max_length=50)),
                ('value', models.DecimalField(decimal_places=4, help_text='Observed environmental value.', max_digits=12)),
                ('unit', models.CharField(help_text='Unit of the observed value.', max_length=50)),
                ('observed_at', models.DateTimeField(help_text='Timestamp represented by the observation.')),
                ('provider_updated_at', models.DateTimeField(blank=True, help_text='Timestamp at which the provider last updated the observation.', null=True)),
                ('fetched_at', models.DateTimeField(help_text='Timestamp when CarbonIQ retrieved the observation.')),
                ('is_estimated', models.BooleanField(default=False, help_text='Whether the provider marked this observation as estimated.')),
                ('estimation_method', models.CharField(blank=True, default='', help_text='Estimation method reported by the provider, if available.', max_length=100)),
                ('temporal_granularity', models.CharField(choices=[('5_minutes', '5 Minutes'), ('15_minutes', '15 Minutes'), ('hourly', 'Hourly')], default='hourly', help_text='Temporal resolution of the observation.', max_length=20)),
                ('emission_factor_type', models.CharField(choices=[('lifecycle', 'Lifecycle'), ('direct', 'Direct')], default='lifecycle', help_text='Emission factor methodology used by the provider.', max_length=20)),
                ('flow_traced', models.BooleanField(default=False, help_text='Whether flow-traced electricity data was used.')),
                ('source_url', models.URLField(help_text='Source URL for traceability.', max_length=500)),
            ],
            options={
                'ordering': ('-observed_at', '-fetched_at'),
                'indexes': [models.Index(fields=['provider', 'data_type', 'zone', 'observed_at'], name='ext_obs_provider_data_idx'), models.Index(fields=['zone', 'observed_at'], name='ext_obs_zone_observed_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'data_type', 'zone', 'observed_at', 'temporal_granularity', 'emission_factor_type', 'flow_traced'), name='unique_external_observation')],
            },
        ),
    ]
