# Generated by Django 6.0.7 on 2026-08-05 17:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('name', models.CharField(help_text='Name of the activity category.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category.')),
                ('unit', models.CharField(help_text='Measurement unit (e.g. kWh, km, litre).', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order in which categories are displayed.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is available for users.')),
            ],
            options={
                'verbose_name': 'Activity Category',
                'verbose_name_plural': 'Activity Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='carbon_acti_is_acti_1e48c1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('display_order__gte', 0)), name='activity_category_display_order_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='CarbonActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Processing status of this submission.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this submission.')),
                ('user', models.ForeignKey(help_text='User who submitted this activity.', on_delete=django.db.models.deletion.CASCADE, related_name='carbon_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carbon Activity',
                'verbose_name_plural': 'Carbon Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('total_emission', models.DecimalField(decimal_places=4, help_text='Total carbon emission (kg CO₂e).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('calculated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the footprint was calculated.')),
                ('calculation_version', models.CharField(default='v1.0', help_text='Version of the calculation algorithm.', max_length=20)),
                ('carbon_activity', models.OneToOneField(help_text='Carbon activity associated with this footprint.', on_delete=django.db.models.deletion.CASCADE, related_name='carbon_footprint', to='carbon.carbonactivity')),
            ],
            options={
                'verbose_name': 'Carbon Footprint',
                'verbose_name_plural': 'Carbon Footprints',
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('factor', models.DecimalField(decimal_places=4, help_text='Emission factor value.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(help_text='Source of this emission factor.', max_length=255)),
                ('effective_from', models.DateField(help_text='Date from which this factor becomes valid.')),
                ('effective_to', models.DateField(blank=True, help_text='Date until which this factor remains valid.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this emission factor is currently active.')),
                ('activity_category', models.ForeignKey(help_text='Activity category associated with this emission factor.', on_delete=django.db.models.deletion.PROTECT, related_name='emission_factors', to='carbon.activitycategory')),
            ],
            options={
                'verbose_name': 'Emission Factor',
                'verbose_name_plural': 'Emission Factors',
                'ordering': ['activity_category', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity entered by the user.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('emission_factor_snapshot', models.DecimalField(decimal_places=4, help_text='Snapshot of the emission factor used.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('entry_emission', models.DecimalField(decimal_places=4, help_text='Calculated emission for this activity.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(help_text='Category selected by the user.', on_delete=django.db.models.deletion.PROTECT, related_name='activity_entries', to='carbon.activitycategory')),
                ('carbon_activity', models.ForeignKey(help_text='Parent carbon activity submission.', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='carbon.carbonactivity')),
                ('emission_factor', models.ForeignKey(help_text='Emission factor used.', on_delete=django.db.models.deletion.PROTECT, related_name='activity_entries', to='carbon.emissionfactor')),
            ],
            options={
                'verbose_name': 'Activity Entry',
                'verbose_name_plural': 'Activity Entries',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='carbonactivity',
            index=models.Index(fields=['status'], name='carbon_carb_status_577bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['is_active'], name='carbon_emis_is_acti_fa9fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['effective_from'], name='carbon_emis_effecti_27c65a_idx'),
        ),
        migrations.AddConstraint(
            model_name='emissionfactor',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='emission_factor_valid_date_range'),
        ),
    ]
