# Generated by Django 6.0.7 on 2026-08-31 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('scope', models.CharField(choices=[('NATIONAL', 'National'), ('DISTRICT', 'District')], help_text='Geographic scope of the benchmark.', max_length=20)),
                ('state', models.CharField(blank=True, help_text='Indian state for district-level benchmarks.', max_length=100, null=True)),
                ('district', models.CharField(blank=True, help_text='Indian district for district-level benchmarks.', max_length=100, null=True)),
                ('reference_period', models.CharField(help_text='Reference period of the source, e.g. 2011-2012 or 2024.', max_length=20)),
                ('value', models.DecimalField(decimal_places=3, help_text='Benchmark value in the stored source unit.', max_digits=12)),
                ('unit', models.CharField(help_text='Original unit of the benchmark value.', max_length=100)),
                ('population_basis', models.CharField(default='per_capita', help_text='Population basis, e.g. per_capita or per_household.', max_length=50)),
                ('source', models.CharField(help_text='Human-readable source or publication name.', max_length=255)),
                ('source_reference', models.URLField(blank=True, help_text='DOI or authoritative source URL.', max_length=500)),
                ('methodology', models.TextField(blank=True, help_text='Description of the benchmark methodology and scope.')),
                ('effective_from', models.DateField(blank=True, help_text='Date from which this benchmark is considered applicable.', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Date until which this benchmark is considered applicable.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this benchmark can currently be selected.')),
            ],
            options={
                'verbose_name': 'Carbon Benchmark',
                'verbose_name_plural': 'Carbon Benchmarks',
                'indexes': [models.Index(fields=['scope', 'state', 'district'], name='carbon_carb_scope_c1ff34_idx'), models.Index(fields=['is_active'], name='carbon_carb_is_acti_40aba6_idx'), models.Index(fields=['reference_period'], name='carbon_carb_referen_9e9abf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('district__isnull', True), ('scope', 'NATIONAL'), ('state__isnull', True)), models.Q(('district__isnull', False), ('scope', 'DISTRICT'), ('state__isnull', False)), _connector='OR'), name='valid_benchmark_geography'), models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='benchmark_value_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('state', models.CharField(help_text='Indian state or union territory.', max_length=100)),
                ('district', models.CharField(help_text='Indian district used for regional benchmarking.', max_length=100)),
                ('user', models.OneToOneField(help_text='CarbonIQ user associated with this geographic context.', on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Location',
                'verbose_name_plural': 'User Locations',
                'indexes': [models.Index(fields=['state'], name='carbon_user_state_7546b2_idx'), models.Index(fields=['state', 'district'], name='carbon_user_state_007893_idx')],
            },
        ),
    ]
