# Generated by Django 6.0.7 on 2026-09-06 12:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('code', models.CharField(help_text='Unique machine-readable achievement code.', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Display name of the achievement.', max_length=150)),
                ('description', models.TextField(help_text='Explanation of what the achievement represents.')),
                ('icon', models.CharField(blank=True, help_text='Optional icon identifier used by the frontend.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this achievement can currently be earned.')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='gamificatio_is_acti_a3b5df_idx')],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('code', models.CharField(help_text='Unique machine-readable challenge code.', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Display title of the challenge.', max_length=200)),
                ('description', models.TextField(help_text='Explanation of the challenge objective.')),
                ('metric', models.CharField(choices=[('EMISSION_REDUCTION', 'Emission Reduction'), ('SUSTAINABLE_ACTIONS', 'Sustainable Actions'), ('MONTHLY_IMPROVEMENT', 'Monthly Improvement'), ('LOW_EMISSION_PERIOD', 'Low Emission Period')], help_text='Measurement used to determine challenge progress.', max_length=50)),
                ('target', models.DecimalField(decimal_places=4, help_text='Target value required to complete the challenge.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField(help_text='Date from which the challenge is available.')),
                ('end_date', models.DateField(help_text='Date after which the challenge expires.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this challenge is currently available.')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['start_date', 'title'],
                'indexes': [models.Index(fields=['is_active'], name='gamificatio_is_acti_21c3b6_idx'), models.Index(fields=['start_date', 'end_date'], name='gamificatio_start_d_ff8bb0_idx'), models.Index(fields=['metric'], name='gamificatio_metric_64acee_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='challenge_valid_date_range')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('earned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the achievement was earned.')),
                ('achievement', models.ForeignKey(help_text='Achievement earned by the user.', on_delete=django.db.models.deletion.PROTECT, related_name='user_achievements', to='gamification.achievement')),
                ('user', models.ForeignKey(help_text='User who earned the achievement.', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', '-earned_at'], name='gamificatio_user_id_30dd99_idx'), models.Index(fields=['achievement'], name='gamificatio_achieve_e7ca42_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement')],
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('progress', models.DecimalField(decimal_places=4, default=0, help_text='Validated challenge progress calculated by the server-side gamification services.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed', models.BooleanField(default=False, help_text='Whether the user has completed the challenge.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the challenge was completed.', null=True)),
                ('challenge', models.ForeignKey(help_text='Challenge joined by the user.', on_delete=django.db.models.deletion.PROTECT, related_name='user_challenges', to='gamification.challenge')),
                ('user', models.ForeignKey(help_text='User participating in the challenge.', on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'completed'], name='gamificatio_user_id_31b82a_idx'), models.Index(fields=['challenge', 'completed'], name='gamificatio_challen_aefa4a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge'), name='unique_user_challenge')],
            },
        ),
    ]
