# Generated by Django 6.0.7 on 2026-08-30 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carbon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('title', models.CharField(help_text='Short title of the recommendation.', max_length=200)),
                ('description', models.TextField(help_text='Detailed explanation of the recommended action.')),
                ('action_type', models.CharField(choices=[('SUSTAINABILITY', 'Sustainability'), ('OFFSET', 'Carbon Offset')], default='SUSTAINABILITY', help_text='Type of action represented by this recommendation.', max_length=20)),
                ('priority', models.PositiveIntegerField(default=50, help_text='Base priority used when ranking recommendations. Higher values indicate greater baseline importance.')),
                ('applicable_segment', models.CharField(blank=True, help_text='Optional interpreted user-segment/profile descriptor for which this recommendation is particularly relevant.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this recommendation is currently available.')),
                ('category', models.ForeignKey(blank=True, help_text='Optional activity category this recommendation primarily addresses.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='carbon.activitycategory')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-priority', 'title'],
                'indexes': [models.Index(fields=['is_active'], name='recommendat_is_acti_c98892_idx'), models.Index(fields=['action_type'], name='recommendat_action__39190f_idx'), models.Index(fields=['category', 'is_active'], name='recommendat_categor_d17ad0_idx')],
            },
        ),
    ]
