# Generated by Django 6.0.7 on 2026-08-30 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('score', models.DecimalField(decimal_places=4, help_text='Personalized relevance score assigned to this recommendation.', max_digits=8)),
                ('reason', models.TextField(help_text='Explanation describing why this recommendation was generated for the user.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISMISSED', 'Dismissed'), ('COMPLETED', 'Completed')], default='ACTIVE', help_text='Current status of the personalized recommendation.', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this recommendation was generated.')),
                ('recommendation', models.ForeignKey(help_text='Recommendation assigned to the user.', on_delete=django.db.models.deletion.PROTECT, related_name='user_recommendations', to='recommendations.recommendation')),
                ('user', models.ForeignKey(help_text='User who received this recommendation.', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-generated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='recommendat_user_id_a8ec50_idx'), models.Index(fields=['user', '-score'], name='recommendat_user_id_469d9e_idx'), models.Index(fields=['recommendation', 'status'], name='recommendat_recomme_6d2b3d_idx')],
            },
        ),
    ]
