# Generated by Django 6.0.7 on 2026-08-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_userrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecommendation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DISMISSED', 'Dismissed'), ('COMPLETED', 'Completed'), ('SUPERSEDED', 'Superseded')], default='ACTIVE', help_text='Current status of the personalized recommendation.', max_length=20),
        ),
    ]
