# Generated by Django 6.0.7 on 2026-09-01 21:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_userrecommendation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffsetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('name', models.CharField(help_text='Registered project name.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Project description obtained from the source registry.')),
                ('project_type', models.CharField(blank=True, help_text='Project type or activity classification.', max_length=150)),
                ('country', models.CharField(blank=True, help_text='Country where the project is located.', max_length=100)),
                ('region', models.CharField(blank=True, help_text='State, province, region, or other geographic subdivision.', max_length=150)),
                ('registry', models.CharField(help_text='External registry name.', max_length=150)),
                ('registry_project_id', models.CharField(help_text='Project identifier assigned by the external registry.', max_length=150)),
                ('registry_url', models.URLField(help_text='Public URL of the project in the external registry.', max_length=500)),
                ('standard', models.CharField(blank=True, help_text='Certification or carbon standard associated with the project.', max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Normalized project status from the source registry.', max_length=20)),
                ('project_scale', models.CharField(blank=True, help_text='Project scale as reported by the source registry.', max_length=100)),
                ('annual_estimated_credits', models.DecimalField(blank=True, decimal_places=2, help_text='Annual estimated carbon credits reported by the registry, when available.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sdg_impacts', models.JSONField(blank=True, default=list, help_text='Structured SDG impact information reported by the source registry.')),
                ('project_developer', models.CharField(blank=True, help_text='Project developer or implementing organization.', max_length=255)),
                ('certification_documents_url', models.URLField(blank=True, help_text='Public certification or project-document URL, when available.', max_length=500)),
                ('source_last_verified_at', models.DateTimeField(help_text='Timestamp when CarbonIQ last verified this project against the source.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this project is currently eligible for recommendations.')),
            ],
            options={
                'verbose_name': 'Offset Project',
                'verbose_name_plural': 'Offset Projects',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['registry'], name='recommendat_registr_9a92fc_idx'), models.Index(fields=['registry_project_id'], name='recommendat_registr_36bb5d_idx'), models.Index(fields=['country'], name='recommendat_country_30dafb_idx'), models.Index(fields=['project_type'], name='recommendat_project_899a2d_idx'), models.Index(fields=['status'], name='recommendat_status_9080a9_idx'), models.Index(fields=['is_active'], name='recommendat_is_acti_39c250_idx')],
                'constraints': [models.UniqueConstraint(fields=('registry', 'registry_project_id'), name='unique_offset_registry_project')],
            },
        ),
        migrations.CreateModel(
            name='OffsetRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.')),
                ('score', models.DecimalField(decimal_places=4, help_text='Personalized relevance score for this project.', max_digits=8)),
                ('reason', models.TextField(help_text='Explanation describing why this offset project was recommended to the user.')),
                ('indicative_tonnes', models.DecimalField(decimal_places=4, help_text='Indicative offset requirement in tonnes CO₂e captured at recommendation-generation time.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISMISSED', 'Dismissed'), ('COMPLETED', 'Completed'), ('SUPERSEDED', 'Superseded')], default='ACTIVE', help_text='Current lifecycle status of this offset recommendation.', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this offset recommendation was generated.')),
                ('offset_project', models.ForeignKey(help_text='Offset project recommended to the user.', on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='recommendations.offsetproject')),
                ('user', models.ForeignKey(help_text='User who received this offset recommendation.', on_delete=django.db.models.deletion.CASCADE, related_name='offset_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offset Recommendation',
                'verbose_name_plural': 'Offset Recommendations',
                'ordering': ['-score', '-generated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='recommendat_user_id_8e9c33_idx'), models.Index(fields=['user', '-score'], name='recommendat_user_id_116469_idx'), models.Index(fields=['offset_project', 'status'], name='recommendat_offset__f76c43_idx')],
            },
        ),
    ]
